name: Web Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Web build
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          export_debug: false
          presets_to_export: "Web"
          cache: true

      - name: Upload downloadable build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vikingr-web-build
          path: ${{ steps.export.outputs.build_directory }}/Web
          retention-days: 14

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.export.outputs.build_directory }}/Web

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
